import logging
from datetime import datetime
from typing import Optional

from backend.app.modules.sapro.oid_compiler.models import OidEntry, SoapTableInfo

logger = logging.getLogger(__name__)

# Tables with known modeling logic (fully implemented)
# Maps entry_name -> handler method name
KNOWN_TABLE_HANDLERS = {
    "rsBWMNetworkEntry": "_generate_bwm_network",
}


class ModelingGenerator:
    """Generate SAPRO TCL modeling files for tables with hidden columns.

    Hidden columns are firmware-computed values that CC doesn't send via SNMP Set.
    This generator creates %after_set_action blocks that simulate the firmware's
    auto-computation logic so the simulator responds correctly to CC operations.
    """

    def __init__(
        self,
        oid_entries: list[OidEntry],
        soap_tables: list[SoapTableInfo],
    ):
        self.oid_entries = oid_entries
        self.soap_tables = soap_tables

        # Build lookup: entry_name -> {col_position -> OidEntry}
        self._entry_columns: dict[str, dict[int, OidEntry]] = {}
        # Build lookup: entry_name -> entry OID
        self._entry_oids: dict[str, str] = {}

        self._build_lookups()

    def _build_lookups(self) -> None:
        """Build mappings from entry names to their column OID entries."""
        # Group columns by table entry name
        table_columns: dict[str, list[OidEntry]] = {}
        for e in self.oid_entries:
            if e.is_table_entry:
                self._entry_oids[e.label] = e.oid
            if e.is_table_column and e.entry_name:
                table_columns.setdefault(e.entry_name, []).append(e)

        # For each table, sort columns by OID and assign positions
        for entry_name, cols in table_columns.items():
            cols.sort(key=lambda c: [int(x) for x in c.oid.split(".")])
            self._entry_columns[entry_name] = {
                i: col for i, col in enumerate(cols, start=1)
            }

    def _get_column_oid(self, entry_name: str, position: int) -> Optional[str]:
        """Get the full OID for a column by entry name and position."""
        cols = self._entry_columns.get(entry_name, {})
        col = cols.get(position)
        return col.oid if col else None

    def _get_column_label(self, entry_name: str, position: int) -> Optional[str]:
        """Get the SNMP label for a column by entry name and position."""
        cols = self._entry_columns.get(entry_name, {})
        col = cols.get(position)
        return col.label if col else None

    def _get_column_syntax(self, entry_name: str, position: int) -> Optional[str]:
        """Get the SNMP syntax for a column by entry name and position."""
        cols = self._entry_columns.get(entry_name, {})
        col = cols.get(position)
        return col.syntax if col else None

    def generate(self) -> str:
        """Generate the complete TCL modeling file content."""
        lines: list[str] = []

        lines.append(self._generate_header())
        lines.append(self._generate_init_action())

        # Generate action blocks for tables with hidden columns
        tables_with_hidden = [
            t for t in self.soap_tables
            if t.hidden_count > 0 and t.entry_name in self._entry_columns
        ]

        for table in tables_with_hidden:
            handler_name = KNOWN_TABLE_HANDLERS.get(table.entry_name)
            if handler_name:
                handler = getattr(self, handler_name)
                block = handler(table)
                if block:
                    lines.append(block)
            else:
                skeleton = self._generate_skeleton(table)
                if skeleton:
                    lines.append(skeleton)

        content = "\n".join(lines) + "\n"
        logger.info(
            f"Generated modeling file: "
            f"{len(tables_with_hidden)} tables, "
            f"{sum(1 for t in tables_with_hidden if t.entry_name in KNOWN_TABLE_HANDLERS)} fully implemented"
        )
        return content

    def _generate_header(self) -> str:
        """Generate the file header comment block."""
        date = datetime.now().strftime("%a %b %d %H:%M:%S %Y")
        return f"""\
# ===================================================================
# DefensePro TCL Modeling File
# Generated by SimulatorTools MIB Compiler
# Date: {date}
#
# This file simulates DefensePro firmware behavior for SNMP Set
# operations on tables with hidden (firmware-computed) columns.
#
# When CyberController sends a Set with only visible columns,
# these scripts auto-compute the hidden column values so the
# simulator behaves like a real DefensePro device.
#
# SAPRO Actions used:
#   %init_action             - Runs at device startup (utility procs)
#   %after_set_action <oid>  - Runs after a Set on matching OID
#
# SAPRO TCL commands used:
#   SA_getreqvb   - Get current Set varbind (oid, type, value)
#   SA_getvar     - Get variable values from the MIB store
#   SA_setvar     - Set variable values in the MIB store
#   SA_getmyip    - Get this device's IP address
#   SA_puts       - Debug output
# ==================================================================="""

    def _generate_init_action(self) -> str:
        """Generate %init_action with reusable utility procedures."""
        return """\

%init_action
    # ---------------------------------------------------------------
    # Device initialization and reusable utility procedures
    # ---------------------------------------------------------------

    set myIP [SA_getmyip]
    # Uncomment the lines below to enable TCL debug logging:
    # SA_settcldebugflag 1
    # SA_settcldebugfile tcl_${myIP}.dbg

    # -----------------------------------------------------------
    # switch_column_oid: Replace the column OID prefix in a full
    # varbind OID, preserving the instance suffix.
    #
    # When SAPRO triggers %after_set_action for a column, the
    # varbind OID has the form:
    #   <entry_oid>.<source_col>.<instance_suffix>
    #
    # This proc swaps <source_col> for <target_col> so we can
    # read or write a different column in the same row.
    #
    # Arguments:
    #   vb_oid         - Full OID from the varbind
    #   source_col_oid - Column OID prefix being replaced
    #                    (e.g., "1.3.6.1.4.1.89.35.1.60.63.1.3")
    #   target_col_oid - Column OID prefix to substitute
    #                    (e.g., "1.3.6.1.4.1.89.35.1.60.63.1.5")
    #
    # Returns: New OID with column swapped, instance preserved
    # -----------------------------------------------------------
    proc switch_column_oid {vb_oid source_col_oid target_col_oid} {
        set instance [string range $vb_oid [string length $source_col_oid] end]
        return "${target_col_oid}${instance}"
    }

    # -----------------------------------------------------------
    # copy_column_value: Copy a varbind's value to another column
    # in the same row. Used when a hidden column is a direct copy
    # of a visible column.
    #
    # Arguments:
    #   varbind        - The Set varbind list {oid type value}
    #   source_col_oid - Column OID prefix of the source
    #   target_col_oid - Column OID prefix of the target
    # -----------------------------------------------------------
    proc copy_column_value {varbind source_col_oid target_col_oid} {
        set src_oid [lindex $varbind 0]
        set src_type [lindex $varbind 1]
        set src_value [lindex $varbind 2]
        set target_oid [switch_column_oid $src_oid $source_col_oid $target_col_oid]
        SA_setvar [list [list $target_oid $src_type $src_value]]
    }

    # -----------------------------------------------------------
    # get_column_value: Read the current value of a column in the
    # same row as a given varbind.
    #
    # Arguments:
    #   vb_oid         - Full OID from the triggering varbind
    #   source_col_oid - Column OID prefix of the triggering column
    #   target_col_oid - Column OID prefix of the column to read
    #
    # Returns: The value of the target column (third element of
    #          the SA_getvar result triplet)
    # -----------------------------------------------------------
    proc get_column_value {vb_oid source_col_oid target_col_oid} {
        set target_oid [switch_column_oid $vb_oid $source_col_oid $target_col_oid]
        set result [SA_getvar [list $target_oid]]
        set triplet [lindex $result 0]
        return [lindex $triplet 2]
    }

    # -----------------------------------------------------------
    # set_column_value: Write a value to a column in the same row
    # as a given varbind.
    #
    # Arguments:
    #   vb_oid         - Full OID from the triggering varbind
    #   source_col_oid - Column OID prefix of the triggering column
    #   target_col_oid - Column OID prefix of the column to write
    #   type           - SNMP type (e.g., "Integer", "OctetString")
    #   value          - The value to set
    # -----------------------------------------------------------
    proc set_column_value {vb_oid source_col_oid target_col_oid type value} {
        set target_oid [switch_column_oid $vb_oid $source_col_oid $target_col_oid]
        SA_setvar [list [list $target_oid $type $value]]
    }

    # -----------------------------------------------------------
    # hex_to_ipv4: Convert a hex string to dotted-decimal IPv4.
    # Handles IPv4-mapped IPv6 format used by DefensePro
    # (e.g., 0x00000000000000000000ffff0a010101 -> 10.1.1.1)
    #
    # Arguments:
    #   hex_string - Hex value (with or without 0x prefix)
    #
    # Returns: IPv4 address in dotted-decimal notation
    # -----------------------------------------------------------
    proc hex_to_ipv4 {hex_string} {
        set hex_string [string trimleft $hex_string "0x"]
        # Take last 8 hex digits (4 bytes) for IPv4
        set hex_string [string range $hex_string end-7 end]
        set hex_string [format "%08s" $hex_string]

        set octet1 [expr 0x[string range $hex_string 0 1]]
        set octet2 [expr 0x[string range $hex_string 2 3]]
        set octet3 [expr 0x[string range $hex_string 4 5]]
        set octet4 [expr 0x[string range $hex_string 6 7]]

        return "$octet1.$octet2.$octet3.$octet4"
    }

    # -----------------------------------------------------------
    # ipv4_to_hex: Convert dotted-decimal IPv4 to DefensePro hex
    # format (IPv4-mapped IPv6: 0x00000000000000000000ffffXXXXXXXX)
    #
    # Arguments:
    #   ip_address - IPv4 in dotted-decimal (e.g., "10.1.1.1")
    #
    # Returns: Hex string in IPv4-mapped IPv6 format
    # -----------------------------------------------------------
    proc ipv4_to_hex {ip_address} {
        set octets [split $ip_address "."]
        set ipv4_hex ""
        foreach octet $octets {
            append ipv4_hex [format "%02x" $octet]
        }
        return "0x00000000000000000000ffff$ipv4_hex"
    }

    # -----------------------------------------------------------
    # compute_broadcast: Calculate the broadcast address from a
    # network address and subnet mask.
    #
    # broadcast = network_ip | (~subnet_mask & 0xFFFFFFFF)
    #
    # Arguments:
    #   network_ip  - Network IP in dotted-decimal
    #   subnet_mask - Subnet mask in dotted-decimal
    #
    # Returns: Broadcast address in dotted-decimal
    # -----------------------------------------------------------
    proc compute_broadcast {network_ip subnet_mask} {
        # Convert IP to 32-bit integer
        proc _ip_to_int {ip} {
            set result 0
            foreach octet [split $ip "."] {
                set result [expr {($result << 8) + $octet}]
            }
            return $result
        }

        # Convert 32-bit integer to IP
        proc _int_to_ip {int_val} {
            return "[expr {($int_val >> 24) & 0xFF}].[expr {($int_val >> 16) & 0xFF}].[expr {($int_val >> 8) & 0xFF}].[expr {$int_val & 0xFF}]"
        }

        set net_int [_ip_to_int $network_ip]
        set mask_int [_ip_to_int $subnet_mask]
        set broadcast_int [expr {$net_int | (~$mask_int & 0xFFFFFFFF)}]
        return [_int_to_ip $broadcast_int]
    }"""

    def _generate_bwm_network(self, table: SoapTableInfo) -> str:
        """Generate modeling for rsBWMNetworkEntry.

        When CC creates a BWM Network, it sets:
          - C1: Name (key)
          - C2: SubIndex (key)
          - C3: Address (visible)
          - C4: Mask (visible)

        Firmware auto-computes:
          - C5: FromIP = copy of Address
          - C6: ToIP = broadcast(Address, Mask)
          - C7: Mode = 1 (ipMask) — default when Address+Mask are provided
          - C8: Status = RowStatus (handled by SAPRO %dcol, no TCL needed)
        """
        entry_oid = self._entry_oids.get("rsBWMNetworkEntry")
        if not entry_oid:
            logger.warning("rsBWMNetworkEntry not found in OID entries")
            return ""

        # Get column OIDs
        address_oid = self._get_column_oid("rsBWMNetworkEntry", 3)
        mask_oid = self._get_column_oid("rsBWMNetworkEntry", 4)
        from_ip_oid = self._get_column_oid("rsBWMNetworkEntry", 5)
        to_ip_oid = self._get_column_oid("rsBWMNetworkEntry", 6)
        mode_oid = self._get_column_oid("rsBWMNetworkEntry", 7)

        if not all([address_oid, mask_oid, from_ip_oid, to_ip_oid, mode_oid]):
            logger.warning("rsBWMNetworkEntry: could not resolve all column OIDs")
            return ""

        # Verify column labels match expectations
        address_label = self._get_column_label("rsBWMNetworkEntry", 3)
        from_ip_label = self._get_column_label("rsBWMNetworkEntry", 5)
        to_ip_label = self._get_column_label("rsBWMNetworkEntry", 6)
        mode_label = self._get_column_label("rsBWMNetworkEntry", 7)

        return f"""\

# ===================================================================
# rsBWMNetworkEntry — BWM Network Classes
# Entry OID: {entry_oid}
#
# Visible columns (set by CC):
#   C3: {address_label} (Address)
#   C4: {self._get_column_label("rsBWMNetworkEntry", 4)} (Mask)
#
# Hidden columns (computed by this script):
#   C5: {from_ip_label} = copy of Address
#   C6: {to_ip_label}   = broadcast(Address, Mask)
#   C7: {mode_label}    = 1 (ipMask mode, default for Address+Mask)
#   C8: Status           = RowStatus (handled by SAPRO %dcol)
# ===================================================================
%after_set_action {address_oid}
    set varbind [SA_getreqvb]
    set vb_oid [lindex $varbind 0]
    set address_hex [lindex $varbind 2]

    # C5 (FromIP) = copy of Address
    copy_column_value $varbind "{address_oid}" "{from_ip_oid}"

    # Read the Mask value from C4 to compute ToIP
    set mask_hex [get_column_value $vb_oid "{address_oid}" "{mask_oid}"]
    # Strip trailing whitespace that SA_getvar may include
    set mask_hex [string trimright $mask_hex]

    # C6 (ToIP) = broadcast(Address, Mask)
    if {{$mask_hex ne "" && $mask_hex ne "0x00000000000000000000ffff00000000"}} {{
        set from_ip [hex_to_ipv4 $address_hex]
        set mask_ip [hex_to_ipv4 $mask_hex]
        set broadcast [compute_broadcast $from_ip $mask_ip]
        set to_ip_hex [ipv4_to_hex $broadcast]
        set_column_value $vb_oid "{address_oid}" "{to_ip_oid}" "OctetString" $to_ip_hex
    }}

    # C7 (Mode) = 1 (ipMask)
    set_column_value $vb_oid "{address_oid}" "{mode_oid}" "Integer" 1"""

    def _generate_skeleton(self, table: SoapTableInfo) -> str:
        """Generate a commented-out skeleton for tables with hidden columns.

        Provides documentation about which columns are hidden and what
        positions they occupy, so the logic can be filled in later.
        """
        entry_name = table.entry_name
        entry_oid = self._entry_oids.get(entry_name, "<unknown>")

        # Skip entirely-hidden tables (internal, no CC interaction)
        if table.visible_count == 0:
            return ""

        # Skip tables without create capability (read-only mirrors)
        # They might need modeling later but are lower priority
        if not table.has_create:
            return ""

        hidden_cols = [c for c in table.columns if c.is_hidden]
        visible_cols = [c for c in table.columns if not c.is_hidden]

        # Build column info lines
        visible_lines = []
        for c in visible_cols:
            label = self._get_column_label(entry_name, c.position) or f"<C{c.position}>"
            key_marker = " (key)" if c.is_key else ""
            visible_lines.append(f"#   C{c.position}: {label} — SOAP: {c.soap_name}{key_marker}")

        hidden_lines = []
        for c in hidden_cols:
            label = self._get_column_label(entry_name, c.position) or f"<C{c.position}>"
            syntax = self._get_column_syntax(entry_name, c.position) or "?"
            col_oid = self._get_column_oid(entry_name, c.position) or "?"
            hidden_lines.append(f"#   C{c.position}: {label} ({syntax}) — OID: {col_oid}")

        # Find a visible non-key column to use as trigger OID suggestion.
        # Prefer non-key columns, but fall back to the first visible column.
        trigger_candidates = [c for c in visible_cols if not c.is_key]
        if not trigger_candidates:
            trigger_candidates = visible_cols
        if trigger_candidates:
            trigger_col = trigger_candidates[0]
            trigger_oid = self._get_column_oid(entry_name, trigger_col.position) or "<trigger_oid>"
            trigger_label = self._get_column_label(entry_name, trigger_col.position) or "?"
        else:
            trigger_oid = "<trigger_oid>"
            trigger_label = "<first_visible_column>"

        visible_block = "\n".join(visible_lines)
        hidden_block = "\n".join(hidden_lines)

        return f"""
# ===================================================================
# {entry_name} — SKELETON (not yet implemented)
# Entry OID: {entry_oid}
# Namespace: {table.soap_namespace or "unknown"}
# {table.visible_count} visible, {table.hidden_count} hidden columns
#
# Visible columns (set by CC):
{visible_block}
#
# Hidden columns (need firmware logic):
{hidden_block}
#
# TODO: Capture real device behavior to determine computation logic
#       for each hidden column, then implement %after_set_action.
# ===================================================================
# %after_set_action {trigger_oid}
#     # Triggered when {trigger_label} is set
#     set varbind [SA_getreqvb]
#     set vb_oid [lindex $varbind 0]
#
#     # TODO: Implement hidden column logic here
#     # Example: copy_column_value $varbind "{trigger_oid}" "<target_col_oid>"
#     # Example: set_column_value $vb_oid "{trigger_oid}" "<target_col_oid>" "Integer" 1"""
