# ===================================================================
# DefensePro TCL Modeling File
# Generated by SimulatorTools MIB Compiler
# Date: Tue Mar 31 12:05:45 2026
#
# This file simulates DefensePro firmware behavior for SNMP Set
# operations on tables with hidden (firmware-computed) columns.
#
# When CyberController sends a Set with only visible columns,
# these scripts auto-compute the hidden column values so the
# simulator behaves like a real DefensePro device.
#
# SAPRO Actions used:
#   %init_action             - Runs at device startup (utility procs)
#   %after_set_action <oid>  - Runs after a Set on matching OID
#
# SAPRO TCL commands used:
#   SA_getreqvb   - Get current Set varbind (oid, type, value)
#   SA_getvar     - Get variable values from the MIB store
#   SA_setvar     - Set variable values in the MIB store
#   SA_getmyip    - Get this device's IP address
#   SA_puts       - Debug output
# ===================================================================

%init_action
    # ---------------------------------------------------------------
    # Device initialization and reusable utility procedures
    # ---------------------------------------------------------------

    set myIP [SA_getmyip]
    set ::init_time [clock seconds]
    SA_settcldebugflag 1
    SA_settcldebugfile tcl_${myIP}.dbg
    SA_puts "\n=== sim_v2.tcl init_action started for $myIP ==="

    # -----------------------------------------------------------
    # switch_column_oid: Replace the column OID prefix in a full
    # varbind OID, preserving the instance suffix.
    #
    # When SAPRO triggers %after_set_action for a column, the
    # varbind OID has the form:
    #   <entry_oid>.<source_col>.<instance_suffix>
    #
    # This proc swaps <source_col> for <target_col> so we can
    # read or write a different column in the same row.
    #
    # Arguments:
    #   vb_oid         - Full OID from the varbind
    #   source_col_oid - Column OID prefix being replaced
    #                    (e.g., "1.3.6.1.4.1.89.35.1.60.63.1.3")
    #   target_col_oid - Column OID prefix to substitute
    #                    (e.g., "1.3.6.1.4.1.89.35.1.60.63.1.5")
    #
    # Returns: New OID with column swapped, instance preserved
    # -----------------------------------------------------------
    proc switch_column_oid {vb_oid source_col_oid target_col_oid} {
        set instance [string range $vb_oid [string length $source_col_oid] end]
        set new_oid "${target_col_oid}${instance}"
        SA_puts "\n  switch_column_oid: $source_col_oid -> $target_col_oid instance=$instance result=$new_oid"
        return $new_oid
    }

    # -----------------------------------------------------------
    # copy_column_value: Copy the current Set varbind's value to
    # another column in the same row. Swaps the OID prefix and
    # passes just the new OID to SA_setvar — SAPRO copies the
    # type and value from the current Set request automatically.
    # This matches the pattern from the working test_snmp.tcl.
    #
    # Arguments:
    #   varbind        - The Set varbind from SA_getreqvb
    #   source_col_oid - Column OID prefix of the source
    #   target_col_oid - Column OID prefix of the target
    # -----------------------------------------------------------
    proc copy_column_value {varbind source_col_oid target_col_oid} {
        SA_puts "\n  copy_column_value: raw varbind=$varbind"
        set curvb [lindex $varbind 0]
        SA_puts "\n  copy_column_value: curvb=$curvb"
        set src_oid [lindex $curvb 0]
        set src_type [lindex $curvb 1]
        set src_value [lindex $curvb 2]
        SA_puts "\n  copy_column_value: src_oid=$src_oid src_type=$src_type src_value=$src_value"
        set target_oid [switch_column_oid $src_oid $source_col_oid $target_col_oid]
        SA_puts "\n  copy_column_value: SA_setvar target_oid=$target_oid type=$src_type value=$src_value"
        SA_setvar [list [list $target_oid $src_type $src_value]]
    }

    # -----------------------------------------------------------
    # get_column_value: Read the current value of a column in the
    # same row. Returns the raw value (third space-separated
    # element from SA_getvar result).
    #
    # Arguments:
    #   vb_oid         - Full OID from the triggering varbind
    #   source_col_oid - Column OID prefix of the triggering column
    #   target_col_oid - Column OID prefix of the column to read
    #
    # Returns: The raw value string
    # -----------------------------------------------------------
    proc get_column_value {vb_oid source_col_oid target_col_oid} {
        set target_oid [switch_column_oid $vb_oid $source_col_oid $target_col_oid]
        SA_puts "\n  get_column_value: SA_getvar target_oid=$target_oid"
        set result [SA_getvar [list $target_oid]]
        SA_puts "\n  get_column_value: raw result=$result"
        set curvb [lindex $result 0]
        SA_puts "\n  get_column_value: curvb=$curvb"
        set val [lindex $curvb 2]
        SA_puts "\n  get_column_value: returning value=$val"
        return $val
    }

    # -----------------------------------------------------------
    # set_column_value: Write a value to a column in the same row
    # as a given varbind.
    #
    # Arguments:
    #   vb_oid         - Full OID from the triggering varbind
    #   source_col_oid - Column OID prefix of the triggering column
    #   target_col_oid - Column OID prefix of the column to write
    #   type           - SNMP type (e.g., "Integer", "OctetString")
    #   value          - The value to set
    # -----------------------------------------------------------
    proc set_column_value {vb_oid source_col_oid target_col_oid type value} {
        set target_oid [switch_column_oid $vb_oid $source_col_oid $target_col_oid]
        SA_puts "\n  set_column_value: SA_setvar oid=$target_oid type=$type value=$value"
        SA_setvar [list [list $target_oid $type $value]]
    }

    # -----------------------------------------------------------
    # hex_to_ipv4: Convert a hex string to dotted-decimal IPv4.
    # Handles IPv4-mapped IPv6 format used by DefensePro
    # (e.g., 0x00000000000000000000ffff0a010101 -> 10.1.1.1)
    #
    # Arguments:
    #   hex_string - Hex value (with or without 0x prefix)
    #
    # Returns: IPv4 address in dotted-decimal notation
    # -----------------------------------------------------------
    proc hex_to_ipv4 {hex_string} {
        set hex_string [string trimleft $hex_string "0x"]
        # Take last 8 hex digits (4 bytes) for IPv4
        set hex_string [string range $hex_string end-7 end]
        set hex_string [format "%08s" $hex_string]

        set octet1 [expr 0x[string range $hex_string 0 1]]
        set octet2 [expr 0x[string range $hex_string 2 3]]
        set octet3 [expr 0x[string range $hex_string 4 5]]
        set octet4 [expr 0x[string range $hex_string 6 7]]

        return "$octet1.$octet2.$octet3.$octet4"
    }

    # -----------------------------------------------------------
    # ipv4_to_hex: Convert dotted-decimal IPv4 to DefensePro hex
    # format (IPv4-mapped IPv6: 0x00000000000000000000ffffXXXXXXXX)
    #
    # Arguments:
    #   ip_address - IPv4 in dotted-decimal (e.g., "10.1.1.1")
    #
    # Returns: Hex string in IPv4-mapped IPv6 format
    # -----------------------------------------------------------
    proc ipv4_to_hex {ip_address} {
        set octets [split $ip_address "."]
        set ipv4_hex ""
        foreach octet $octets {
            append ipv4_hex [format "%02x" $octet]
        }
        return "0x00000000000000000000ffff$ipv4_hex"
    }

    # -----------------------------------------------------------
    # compute_broadcast: Calculate the broadcast address from a
    # network address and subnet mask.
    #
    # broadcast = network_ip | (~subnet_mask & 0xFFFFFFFF)
    #
    # Arguments:
    #   network_ip  - Network IP in dotted-decimal
    #   subnet_mask - Subnet mask in dotted-decimal
    #
    # Returns: Broadcast address in dotted-decimal
    # -----------------------------------------------------------
    proc compute_broadcast {network_ip subnet_mask} {
        # Convert IP to 32-bit integer
        proc _ip_to_int {ip} {
            set result 0
            foreach octet [split $ip "."] {
                set result [expr {($result << 8) + $octet}]
            }
            return $result
        }

        # Convert 32-bit integer to IP
        proc _int_to_ip {int_val} {
            return "[expr {($int_val >> 24) & 0xFF}].[expr {($int_val >> 16) & 0xFF}].[expr {($int_val >> 8) & 0xFF}].[expr {$int_val & 0xFF}]"
        }

        set net_int [_ip_to_int $network_ip]
        set mask_int [_ip_to_int $subnet_mask]
        set broadcast_int [expr {$net_int | (~$mask_int & 0xFFFFFFFF)}]
        return [_int_to_ip $broadcast_int]
    }

    # -----------------------------------------------------------
    # decode_string_instance: Parse a string-indexed table instance
    # suffix to extract the name string and subindex.
    #
    # Instance format: .<length>.<ascii_bytes...>.<subindex>
    # Example: .5.116.101.115.116.50.0 = "test2", subindex 0
    #
    # Arguments:
    #   instance  - The instance suffix (e.g., ".5.116.101.115.116.50.0")
    #
    # Returns: list of {name subindex}
    # -----------------------------------------------------------
    proc decode_string_instance {instance} {
        # Remove leading dot
        set parts [split [string range $instance 1 end] "."]
        SA_puts "\n  decode_string_instance: parts=$parts"
        set name_len [lindex $parts 0]
        set name_str ""
        for {set i 1} {$i <= $name_len} {incr i} {
            set ascii_val [lindex $parts $i]
            append name_str [format "%c" $ascii_val]
        }
        set subindex [lindex $parts [expr {$name_len + 1}]]
        SA_puts "\n  decode_string_instance: name=$name_str subindex=$subindex"
        return [list $name_str $subindex]
    }

    # -----------------------------------------------------------
    # mirror_to_current: Copy a Set varbind from a Modify table
    # to its corresponding Current table.
    #
    # DefensePro has paired tables: "Modify" tables hold candidate
    # config, "Current" tables hold active config. When CC writes
    # to a Modify table, this proc mirrors the value to Current
    # so CC sees it as active configuration.
    #
    # The OID translation is simple: replace the Modify entry OID
    # prefix with the Current entry OID prefix. The column number
    # and instance suffix stay the same.
    #
    # Arguments:
    #   varbind          - The Set varbind list {oid type value}
    #   modify_entry_oid - Entry OID of the Modify table
    #   current_entry_oid - Entry OID of the Current table
    # -----------------------------------------------------------
    proc mirror_to_current {varbind modify_entry_oid current_entry_oid} {
        SA_puts "\n  mirror_to_current: raw varbind=$varbind"
        set curvb [lindex $varbind 0]
        set vb_oid [lindex $curvb 0]
        set vb_type [lindex $curvb 1]
        set vb_value [lindex $curvb 2]
        set suffix [string range $vb_oid [string length $modify_entry_oid] end]
        set target_oid "${current_entry_oid}${suffix}"
        SA_puts "\n  mirror_to_current: src=$vb_oid -> target=$target_oid type=$vb_type value=$vb_value"
        SA_setvar [list [list $target_oid $vb_type $vb_value]]
    }

    # -----------------------------------------------------------
    # encode_octetstring_index: Convert a string to SNMP OctetString
    # index format: length.byte1.byte2...
    # E.g., "AD" -> "2.65.68"
    # -----------------------------------------------------------
    proc encode_octetstring_index {text} {
        set len [string length $text]
        set result $len
        for {set i 0} {$i < $len} {incr i} {
            scan [string index $text $i] %c ascii
            append result ".$ascii"
        }
        return $result
    }

    # -----------------------------------------------------------
    # encode_implied_index: Convert a string to SNMP IMPLIED index
    # format: byte1.byte2... (no length prefix).
    # Used for tables with IMPLIED string indexes like
    # snmpTargetAddrName, snmpTargetParamsName, snmpNotifyName.
    # E.g., "public" -> "112.117.98.108.105.99"
    # -----------------------------------------------------------
    proc encode_implied_index {text} {
        set result ""
        for {set i 0} {$i < [string length $text]} {incr i} {
            scan [string index $text $i] %c ascii
            if {$result ne ""} {
                append result "."
            }
            append result $ascii
        }
        return $result
    }

    # -----------------------------------------------------------
    # load_geo_feed_countries: Read geo feed country data from a
    # JSON file and populate rsGeoFeedCountriesTable via SA_setvar.
    # On real devices, firmware populates this table. On simulated
    # devices, this proc does it at startup.
    #
    # JSON format: {"countries": [{"id":"XX","name":"YYY","region":"ZZZ"}, ...]}
    # File path: /opt/sapro/shared/geo_feed_countries.json
    # -----------------------------------------------------------
    proc load_geo_feed_countries {} {
        set json_path "/opt/sapro/shared/geo_feed_countries.json"
        if {![file exists $json_path]} {
            SA_puts "\n  load_geo_feed_countries: $json_path not found, skipping"
            return
        }

        SA_puts "\n  load_geo_feed_countries: loading from $json_path"
        set fp [open $json_path r]
        set json_data [read $fp]
        close $fp

        set base_oid "1.3.6.1.4.1.89.35.1.65.182.3.1"
        # Column suffixes: .1=CountryId, .2=CountryName, .3=CountryRegion, .4=RowStatus

        # Extract country entries using regex
        set pattern {"id":\s*"([^"]+)",\s*"name":\s*"([^"]+)",\s*"region":\s*"([^"]+)"}
        set matches [regexp -all -inline $pattern $json_data]

        set count 0
        for {set i 0} {$i < [llength $matches]} {incr i 4} {
            set id [lindex $matches [expr {$i + 1}]]
            set name [lindex $matches [expr {$i + 2}]]
            set region [lindex $matches [expr {$i + 3}]]
            set instance [encode_octetstring_index $id]

            # Create row: set Name, Region, then RowStatus=createAndGo(4)
            SA_setvar [list \
                [list "${base_oid}.2.${instance}" OctetString $name] \
                [list "${base_oid}.3.${instance}" OctetString $region] \
                [list "${base_oid}.4.${instance}" Integer 4] \
            ]
            incr count
        }
        SA_puts "\n  load_geo_feed_countries: populated $count countries"
    }

    # -----------------------------------------------------------
    # populate_software_version: Create one row in rsFSapplList
    # so CC shows the Software Version Management screen.
    # Reads the version from rndBrgVersion.0 (already in VAR).
    # Image name format: DefensePro_VA_{version}_b110
    # -----------------------------------------------------------
    proc populate_software_version {} {
        # Read version from existing scalar
        set result [SA_getvar {rndBrgVersion.0}]
        set curvb [lindex $result 0]
        set version [lindex $curvb 2]
        SA_puts "\n  populate_software_version: version=$version"

        set image_name "DefensePro_VA_${version}_b110"

        # Build OctetString instance: length.ascii_bytes
        set instance [encode_octetstring_index $image_name]
        SA_puts "\n  populate_software_version: image=$image_name instance=$instance"

        set base "1.3.6.1.4.1.89.35.1.99.1.1"

        # C1:  rsFSapplName (index, auto from dfixed)
        # C2:  rsFSapplIndex = 1
        # C3:  rsFSapplValid = 1 (true)
        # C4:  rsFSapplActive = 1 (true)
        # C5:  rsFSapplVersion = version
        # C6:  rsFSapplStartup = 2 (false)
        # C7:  rsFSapplStatus = createAndGo (4)
        # C8:  rsFSapplVersionOS = version
        # C9:  rsFSapplVersionDP = version
        # C10: rsFSapplVersionDME = N/A
        # C11: rsFSapplVersionDD = version

        # Step 1: Create row via RowStatus createAndGo (C2-C7 only, matches %dcol count)
        SA_setvar [list \
            [list "${base}.2.${instance}" Integer 1] \
            [list "${base}.3.${instance}" Integer 1] \
            [list "${base}.4.${instance}" Integer 1] \
            [list "${base}.5.${instance}" OctetString $version] \
            [list "${base}.6.${instance}" Integer 2] \
            [list "${base}.7.${instance}" Integer 4] \
        ]
        # Step 2: Set C8-C11 (now in %dcol) after row exists
        SA_setvar [list \
            [list "${base}.8.${instance}" OctetString $version] \
            [list "${base}.9.${instance}" OctetString $version] \
            [list "${base}.10.${instance}" OctetString "N/A"] \
            [list "${base}.11.${instance}" OctetString $version] \
        ]
        SA_puts "\n  populate_software_version: created row for $image_name"
    }

    # -----------------------------------------------------------
    # populate_snmp_infrastructure: Pre-populate SNMP infrastructure
    # tables required for CyberController discovery and trap config.
    #
    # Creates rows in:
    #   - snmpTargetAddrTable (trap destinations)
    #   - snmpTargetParamsTable (trap security params)
    #   - snmpNotifyTable (notification config)
    #   - snmpTargetAddrExtTable (extended addr columns)
    #
    # All indexes are IMPLIED OctetString — use encode_implied_index.
    # Row creation via RowStatus createAndGo(4).
    #
    # Reference: DPX_10-6.var lines 49957-50139
    # -----------------------------------------------------------
    proc populate_snmp_infrastructure {} {
        # Entry OIDs
        set addr_base    "1.3.6.1.6.3.12.1.2.1"
        set params_base  "1.3.6.1.6.3.12.1.3.1"
        set notify_base  "1.3.6.1.6.3.13.1.1.1"
        set addr_ext_base "1.3.6.1.6.3.18.1.2.1"

        # Note: snmpTargetAddrTable and snmpTargetParamsTable are NOT
        # pre-populated — CC creates its own entries during sync.

        # --- snmpNotifyTable: "allTraps" entry ---
        # Note: snmpNotifyEntry may not be in CMF if SNMP-NOTIFICATION-MIB
        # was not in the MIB archive. Wrap in catch to not abort init.
        set inst [encode_implied_index "allTraps"]
        if {[catch {
            SA_setvar [list \
                [list "${notify_base}.2.${inst}" OctetString "v3Traps"] \
                [list "${notify_base}.3.${inst}" Integer 1] \
                [list "${notify_base}.4.${inst}" Integer 3] \
                [list "${notify_base}.5.${inst}" Integer 4] \
            ]
            SA_puts "\n  snmpNotify: created allTraps"
        } err]} {
            SA_puts "\n  snmpNotify: SKIPPED ($err)"
        }

        # --- VACM: vacmSecurityToGroupTable ---
        # Index: securityModel(Integer) . securityName(IMPLIED OctetString)
        # From real DP defaults (excluding User Based entries)
        set group_base "1.3.6.1.6.3.16.1.2.1"
        foreach {secmodel secname groupname} {
            1  public            initial
            1  ReadOnlySecurity  InitialReadOnly
            2  public            initial
            2  ReadOnlySecurity  InitialReadOnly
        } {
            set name_len [string length $secname]
            set inst "${secmodel}.${name_len}.[encode_implied_index $secname]"
            if {[catch {
                SA_setvar [list \
                    [list "${group_base}.1.${inst}" Integer $secmodel] \
                    [list "${group_base}.2.${inst}" OctetString $secname] \
                    [list "${group_base}.3.${inst}" OctetString $groupname] \
                    [list "${group_base}.4.${inst}" Integer 3] \
                    [list "${group_base}.5.${inst}" Integer 4] \
                ]
                SA_puts "\n  vacmGroup: ${secmodel}/${secname} -> ${groupname}"
            } err]} {
                SA_puts "\n  vacmGroup ${secmodel}/${secname}: FAILED ($err)"
            }
        }

        # --- VACM: vacmAccessTable ---
        # Index: groupName(len-prefixed) . contextPrefix(len-prefixed) . securityModel(Int) . securityLevel(Int)
        # securityLevel: 1=noAuthNoPriv, 2=authNoPriv, 3=authPriv
        set access_base "1.3.6.1.6.3.16.1.4.1"
        # Note: initial/1/1 is NOT pre-populated — CC creates it during sync.
        # Pre-populating it causes inconsistentValue when CC sends createAndGo.
        foreach {groupname secmodel seclevel readview writeview notifyview} {
            initial          2  1  iso           iso   iso
            initial          3  3  iso           iso   iso
            InitialReadOnly  1  1  ReadOnlyView  None  None
            InitialReadOnly  2  1  ReadOnlyView  None  None
            InitialReadOnly  3  3  ReadOnlyView  None  None
        } {
            # groupName is length-prefixed OctetString index
            set gname_len [string length $groupname]
            set gname_idx "${gname_len}.[encode_implied_index $groupname]"
            # contextPrefix is empty string: length 0, no bytes
            set ctx_idx "0"
            set inst "${gname_idx}.${ctx_idx}.${secmodel}.${seclevel}"
            if {[catch {
                SA_setvar [list \
                    [list "${access_base}.4.${inst}" Integer 1] \
                    [list "${access_base}.5.${inst}" OctetString $readview] \
                    [list "${access_base}.6.${inst}" OctetString $writeview] \
                    [list "${access_base}.7.${inst}" OctetString $notifyview] \
                    [list "${access_base}.8.${inst}" Integer 3] \
                    [list "${access_base}.9.${inst}" Integer 4] \
                ]
                # .4=contextMatch(exact=1), .5=readView, .6=writeView,
                # .7=notifyView, .8=storageType(3), .9=rowStatus(createAndGo=4)
                SA_puts "\n  vacmAccess: ${groupname}/${secmodel}/${seclevel}"
            } err]} {
                SA_puts "\n  vacmAccess ${groupname}/${secmodel}/${seclevel}: FAILED ($err)"
            }
        }

        # --- VACM: vacmViewTreeFamilyTable ---
        # Index: viewName(len-prefixed) . subtree(len-prefixed OID)
        # type: 1=included, 2=excluded
        set view_base "1.3.6.1.6.3.16.1.5.2.1"
        foreach {viewname subtree type} {
            iso           1                        1
            None          1                        2
            ReadOnlyView  1                        1
            ReadOnlyView  1.3.6.1.6.3.16.1.2      2
            ReadOnlyView  1.3.6.1.6.3.16.1.4      2
            ReadOnlyView  1.3.6.1.6.3.16.1.5      2
            ReadOnlyView  1.3.6.1.6.3.18.1.1      2
            ReadOnlyView  1.3.6.1.4.1.89.2.7.2    2
            ReadOnlyView  1.3.6.1.4.1.89.35.1.61  2
            ReadOnlyView  1.3.6.1.6.3.15.1.2.2    2
        } {
            # viewName is length-prefixed
            set vname_len [string length $viewname]
            set vname_idx "${vname_len}.[encode_implied_index $viewname]"
            # subtree is length-prefixed OID (number of sub-identifiers . oid)
            set oid_parts [split $subtree "."]
            set oid_len [llength $oid_parts]
            set subtree_idx "${oid_len}.${subtree}"
            set inst "${vname_idx}.${subtree_idx}"
            if {[catch {
                SA_setvar [list \
                    [list "${view_base}.3.${inst}" OctetString ""] \
                    [list "${view_base}.4.${inst}" Integer $type] \
                    [list "${view_base}.5.${inst}" Integer 3] \
                    [list "${view_base}.6.${inst}" Integer 4] \
                ]
                # .3=mask(empty), .4=type, .5=storageType(3), .6=rowStatus(createAndGo=4)
                SA_puts "\n  vacmView: ${viewname}/${subtree} type=${type}"
            } err]} {
                SA_puts "\n  vacmView ${viewname}/${subtree}: FAILED ($err)"
            }
        }

        SA_puts "\n  populate_snmp_infrastructure: complete"
    }

    # Load geo feed countries at startup
    load_geo_feed_countries

    # Populate software version table
    populate_software_version

    # Populate SNMP infrastructure tables (trap targets, params, notify)
    populate_snmp_infrastructure

    # Pre-populate snmpCommunityTable with "public" community entry
    # CC reads this during discovery to map community string to security context.
    set comm_instance "112.117.98.108.105.99"
    set comm_base "1.3.6.1.6.3.18.1.1.1"
    set rawmac_for_engine [SA_getmymac]
    if {$rawmac_for_engine eq "none"} {
        set rawmac_for_engine "010203040506"
    }
    set engine_id "0x8000005903${rawmac_for_engine}"
    if {[catch {
        SA_setvar [list \
            [list "${comm_base}.2.${comm_instance}" OctetString "public"] \
            [list "${comm_base}.3.${comm_instance}" OctetString "public"] \
            [list "${comm_base}.4.${comm_instance}" OctetString $engine_id] \
            [list "${comm_base}.5.${comm_instance}" OctetString ""] \
            [list "${comm_base}.6.${comm_instance}" OctetString ""] \
            [list "${comm_base}.7.${comm_instance}" Integer 3] \
            [list "${comm_base}.8.${comm_instance}" Integer 4] \
        ]
        SA_puts "\n  snmpCommunity: created 'public' with engineID=$engine_id"
    } err]} {
        SA_puts "\n  snmpCommunity: FAILED ($err)"
    }

    # Set rsWSDSysBaseMACAddress as colon-separated string
    # CC expects format "00:50:56:90:a3:92", not raw bytes
    # Use full OID (1.3.6.1.4.1.89.35.1.69.5.0) — label-based SA_setvar
    # may fail for some scalars.
    set rawmac [SA_getmymac]
    SA_puts "\n  raw MAC from SA_getmymac: $rawmac"
    if {$rawmac eq "none" || [string length $rawmac] < 12} {
        # No MAC assigned — use SAPRO's default (same as $$MYMAINMACADDR$$ substitution)
        set rawmac "010203040506"
        SA_puts "\n  Using default MAC: $rawmac"
    }
    # rawmac is like "005056a51d0c" — format with colons
    set formatted "[string range $rawmac 0 1]:[string range $rawmac 2 3]:[string range $rawmac 4 5]:[string range $rawmac 6 7]:[string range $rawmac 8 9]:[string range $rawmac 10 11]"
    SA_setvar [list [list "1.3.6.1.4.1.89.35.1.69.5.0" OctetString $formatted]]
    SA_puts "\n  Set rsWSDSysBaseMACAddress.0 = $formatted (via OID)"

# ===================================================================
# rsBWMVLANTagGroupEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.60.47.1
# Namespace: radware.Classes.ContextTagGroup
# 5 visible, 1 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C6: rsBWMVLANTagGroupStatus (Integer) — [RowStatus]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# rsBWMBwmPortOperationEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.60.27.1
# Namespace: radware.BWM.Parameters
# 3 visible, 1 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C4: rsBWMBwmOperationStatus (Integer) — [RowStatus]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# rsSSLCertificateEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.148.2.1
# Namespace: radware.Security.SSLCertificates
# 18 visible, 1 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C14: rsSSLCertificateStatus (Integer) — [RowStatus]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# rsBWMNetworkEntry — BWM Network Classes
# Entry OID: 1.3.6.1.4.1.89.35.1.60.63.1
#
# Visible columns (set by CC):
#   C3: rsBWMNetworkAddress (Address)
#   C4: rsBWMNetworkMask (Mask)
#
# Hidden columns (computed by this script):
#   C5: rsBWMNetworkFromIP = copy of Address
#   C6: rsBWMNetworkToIP   = broadcast(Address, Mask)
#   C7: rsBWMNetworkMode    = 1 (ipMask mode, default for Address+Mask)
#   C8: Status           = RowStatus (handled by SAPRO %dcol)
#
# All columns are also mirrored to rsBWMCurrentNetworkEntry.
# ===================================================================
%after_set_action 1.3.6.1.4.1.89.35.1.60.63.1.3
    SA_puts "\n=== after_set_action FIRED for 1.3.6.1.4.1.89.35.1.60.63.1.3 ==="
    set varbind [SA_getreqvb]
    SA_puts "\n  raw SA_getreqvb result: $varbind"
    set curvb [lindex $varbind 0]
    SA_puts "\n  curvb (lindex 0): $curvb"
    set vb_oid [lindex $curvb 0]
    set vb_type [lindex $curvb 1]
    set address_hex [lindex $curvb 2]
    SA_puts "\n  vb_oid=$vb_oid vb_type=$vb_type address_hex=$address_hex"
    set to_ip_hex ""

    # Fix C1 (Name) and C2 (SubIndex) — decode from instance OID
    SA_puts "\n--- Step 0: Decode instance to fix Name and SubIndex ---"
    set instance [string range $vb_oid [string length "1.3.6.1.4.1.89.35.1.60.63.1.3"] end]
    set decoded [decode_string_instance $instance]
    set name_str [lindex $decoded 0]
    set subindex [lindex $decoded 1]
    SA_puts "\n  Setting C1 (Name) = $name_str"
    set name_oid [switch_column_oid $vb_oid "1.3.6.1.4.1.89.35.1.60.63.1.3" "1.3.6.1.4.1.89.35.1.60.63.1.1"]
    SA_setvaltype [list [list $name_oid OctetString "fixed($name_str)"]]
    SA_puts "\n  Setting C2 (SubIndex) = $subindex"
    set subindex_oid [switch_column_oid $vb_oid "1.3.6.1.4.1.89.35.1.60.63.1.3" "1.3.6.1.4.1.89.35.1.60.63.1.2"]
    SA_setvaltype [list [list $subindex_oid OctetString "fixed($subindex)"]]

    # C5 (FromIP) = copy of Address
    SA_puts "\n--- Step 1: Copy Address to FromIP ---"
    copy_column_value $varbind "1.3.6.1.4.1.89.35.1.60.63.1.3" "1.3.6.1.4.1.89.35.1.60.63.1.5"

    # Read the Mask value from C4 to compute ToIP
    SA_puts "\n--- Step 2: Read Mask from C4 ---"
    set mask_hex [get_column_value $vb_oid "1.3.6.1.4.1.89.35.1.60.63.1.3" "1.3.6.1.4.1.89.35.1.60.63.1.4"]
    SA_puts "\n  mask_hex before trimright: '$mask_hex'"
    set mask_hex [string trimright $mask_hex]
    SA_puts "\n  mask_hex after trimright: '$mask_hex'"

    # C6 (ToIP) = broadcast(Address, Mask)
    SA_puts "\n--- Step 3: Compute ToIP (broadcast) ---"
    if {$mask_hex ne "" && $mask_hex ne "0.0.0.0"} {
        set from_ip [hex_to_ipv4 $address_hex]
        SA_puts "\n  from_ip (dotted): $from_ip"
        SA_puts "\n  mask (already dotted): $mask_hex"
        set broadcast [compute_broadcast $from_ip $mask_hex]
        SA_puts "\n  broadcast: $broadcast"
        set to_ip_hex [ipv4_to_hex $broadcast]
        SA_puts "\n  to_ip_hex: $to_ip_hex"
        set_column_value $vb_oid "1.3.6.1.4.1.89.35.1.60.63.1.3" "1.3.6.1.4.1.89.35.1.60.63.1.6" "OctetString" $to_ip_hex
    } else {
        SA_puts "\n  SKIPPED: mask is empty or 0.0.0.0"
    }

    # C7 (Mode) = 1 (ipMask)
    SA_puts "\n--- Step 4: Set Mode to 1 ---"
    set_column_value $vb_oid "1.3.6.1.4.1.89.35.1.60.63.1.3" "1.3.6.1.4.1.89.35.1.60.63.1.7" "Integer" 1

    SA_puts "\n--- Step 5: Mirror to Current table ---"

    # Mirror data columns (C3-C7) to Current table (rsBWMCurrentNetworkEntry)
    # Skip index columns C1 (Name) and C2 (SubIndex) — SAPRO handles
    # those from the OID instance when the row is created.
    set instance [string range $vb_oid [string length "1.3.6.1.4.1.89.35.1.60.63.1.3"] end]
    SA_puts "\n  mirror instance suffix: $instance"
    foreach col_suffix {.3 .4 .5 .6 .7} {
        set full_modify_oid "1.3.6.1.4.1.89.35.1.60.63.1${col_suffix}${instance}"
        SA_puts "\n  mirror: reading $full_modify_oid"
        set getresult [SA_getvar [list $full_modify_oid]]
        SA_puts "\n  mirror: SA_getvar raw result=$getresult"
        set curvb [lindex $getresult 0]
        set col_type [lindex $curvb 1]
        set col_value [lindex $curvb 2]
        set full_current_oid "1.3.6.1.4.1.89.35.1.60.64.1${col_suffix}${instance}"
        SA_puts "\n  mirror: writing $full_current_oid type=$col_type value=$col_value"
        SA_setvar [list [list $full_current_oid $col_type $col_value]]
    }
    SA_puts "\n=== after_set_action COMPLETE ==="


# ===================================================================
# rsBWMFilterEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.60.15.1
# Namespace: radware.Classes.Services
# 20 visible, 6 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C4: rsBWMFilterDestinationPort (Integer) — [default from %dcol]
#   C5: rsBWMFilterSourceFromPort (Integer) — [default from %dcol]
#   C6: rsBWMFilterSourceToPort (Integer) — [default from %dcol]
#   C15: rsBWMFilterType (Integer) — [default from %dcol]
#   C16: rsBWMFilterStatus (Integer) — [RowStatus]
#   C22: rsBWMFilterDestinationMaxPort (Integer) — [default from %dcol]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# rsBWMPhysicalPortGroupEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.60.36.1
# Namespace: radware.Classes.PhysicalPortGroup
# 2 visible, 1 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C3: rsBWMPhysicalPortGroupOperationStatus (Integer) — [RowStatus]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# usmUserEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.6.3.15.1.2.2.1
# Namespace: radware.Management.Snmp
# 5 visible, 8 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C1: usmUserEngineID (OctetString) — [default from %dcol]
#   C3: usmUserSecurityName (OctetString) — [default from %dcol]
#   C4: usmUserCloneFrom (ObjectID) — [default from %dcol]
#   C7: usmUserOwnAuthKeyChange (OctetString) — [default from %dcol]
#   C10: usmUserOwnPrivKeyChange (OctetString) — [default from %dcol]
#   C11: usmUserPublic (OctetString) — [default from %dcol]
#   C12: usmUserStorageType (Integer) — [default from %dcol]
#   C13: usmUserStatus (Integer) — [RowStatus]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# rsBWMRulesEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.60.1.1
# Namespace: radware.BWM.Policies
# 15 visible, 12 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C5: rsBWMRulesStatus (Integer) — [RowStatus]
#   C6: rsBWMRulesAction (Integer) — [default from %dcol]
#   C9: rsBWMRulesPhysicalPort (Integer) — [default from %dcol]
#   C10: rsBWMRulesType (Integer) — [default from %dcol]
#   C16: rsBWMRulesDSCPMarking (Integer) — [default from %dcol]
#   C17: rsBWMRulesReportBlockedPackets (Integer) — [default from %dcol]
#   C19: rsBWMRulesSpecific (OctetString) — [default from %dcol]
#   C22: rsBWMRulesTrafficIdentification (Integer) — [default from %dcol]
#   C23: rsBWMRulesTrafficFlowMaxBW (Integer) — [default from %dcol]
#   C24: rsBWMRulesMaxConcurrentSessions (Integer) — [default from %dcol]
#   C25: rsBWMRulesTrafficIDCookieField (OctetString) — [default from %dcol]
#   C26: rsBWMRulesPolicyGroup (OctetString) — [default from %dcol]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# rsBWMAppPortGroupEntry — NO TCL NEEDED
# Entry OID: 1.3.6.1.4.1.89.35.1.60.56.1
# Namespace: radware.Classes.ApplicationPortGroup
# 4 visible, 1 hidden columns
#
# Hidden columns are all handled by SAPRO's %dcol defaults:
#   C5: rsBWMAppPortGroupStatus (Integer) — [RowStatus]
#
# RowStatus columns are managed by SAPRO's rowstatus(1) value type.
# Default-value columns get their initial values from %dcol in the
# VAR file. CC does not read these hidden columns.
# ===================================================================

# ===================================================================
# Dynamic uptime — returns elapsed time since device start on every GET
# ===================================================================
%getvalue_action 1.3.6.1.4.1.89.35.1.69.2.0
    set now [clock seconds]
    set elapsed [expr {$now - $::init_time}]
    set days [expr {$elapsed / 86400}]
    set hours [expr {($elapsed % 86400) / 3600}]
    set minutes [expr {($elapsed % 3600) / 60}]
    set secs [expr {$elapsed % 60}]
    SA_setcurvalue "$days days $hours hours $minutes minutes $secs seconds"

# ===================================================================
# Dynamic date/time — returns real current date/time on every GET
# ===================================================================
%getvalue_action rsWSDSysManagedDate.0
    SA_setcurvalue [clock format [clock seconds] -format "%d/%m/%Y"]

%getvalue_action rsWSDSysManagedTime.0
    SA_setcurvalue [clock format [clock seconds] -format "%H:%M:%S"]

%getvalue_action rndManagedDate.0
    SA_setcurvalue [clock format [clock seconds] -format "%d%m%Y"]

%getvalue_action rndManagedTime.0
    SA_setcurvalue [clock format [clock seconds] -format "%H%M%S"]

# ===================================================================
# MODELING FILE SUMMARY
#
# Fully implemented (TCL computation logic):
#   - rsBWMNetworkEntry
#
# Modify -> Current table mirroring:
#   - rsBWMRulesEntry -> rsBWMCurrentRulesEntry
#   - rsBWMRulesIPObjectEntry -> rsBWMCurrentRulesIPObjectEntry
#   - rsBWMDSCPEntry -> rsBWMCurrentDSCPEntry
#   - rsBWMPhysicalPortGroupEntry -> rsBWMCurrentPhysicalPortGroupEntry
#   - rsBWMVLANTagGroupEntry -> rsBWMCurrentVLANTagGroupEntry
#   - rsBWMMacGroupEntry -> rsBWMMacGroupCurrentEntry
#   - rsBWMAppPortGroupEntry -> rsBWMCurrentAppPortGroupEntry
#   - rsBWMExtRulesEntry -> rsBWMCurrentExtRulesEntry
#   - rsBWMNetworkEntry -> rsBWMCurrentNetworkEntry
#   - rsBWMPolicyEntry -> rsBWMCurrentPolicyEntry
#   - rsBWMExtPolicyEntry -> rsBWMCurrentExtPolicyEntry
#
# No TCL needed (RowStatus + defaults handled by %dcol):
#   - rsBWMVLANTagGroupEntry
#   - rsBWMBwmPortOperationEntry
#   - rsSSLCertificateEntry
#   - rsBWMFilterEntry
#   - rsBWMPhysicalPortGroupEntry
#   - usmUserEntry
#   - rsBWMRulesEntry
#   - rsBWMAppPortGroupEntry
#
# Needs investigation (may need TCL after Phase 3 analysis):
#   (none)

# ===================================================================
# Test: does %check_set_action fire for ext table OIDs?
# If SAPRO's internal validation rejects before calling TCL, this
# won't appear in the debug log.
# ===================================================================
# TEMPORARY DEBUG — remove after investigation
%after_set_action 1.3.6.1.6.3.12.1.2.1.9
    SA_puts "\n  AFTER_SET_HIT targetAddr rowStatus"
    SA_puts "\n    vb: [SA_getreqvb]"
    SA_puts "\n    all: [SA_getreqvars]"
