import logging
from datetime import datetime

from backend.app.modules.sapro.oid_compiler.constants import SYNTAX_MAP
from backend.app.modules.sapro.oid_compiler.models import (
    AccessLevel,
    DynamicRowConfig,
    DynamicRowType,
    OidEntry,
)

logger = logging.getLogger(__name__)

# File header matching the real SAPRO teaching agent output format
VAR_HEADER = """####################################################
# Generated by Simulator Tools MIB Compiler
# Date:                 {date}
# Value type formats:
#     fixed(current_value)
#     lastset(initial_value)
#     r_lastset(min, max,initial_value)
#     random(starting_value,max_delta)
#     randomup(starting_value,max_delta)
#     clock(starting_value)
#     sequential(min_value,max_value)
#     seqinc(min_value,increment,max_value)
#     seqtimeinc(min_value,increment,max_value)
#     dfixed(current_value)
#     rowstatus(current_value)
#     testandinc(current_value)
#     utilization(min_value,max_delta,max_value)
#     valuelist(a, b, c, d, e, ...)
#     fastclock(starting_value, multiplier)
#     valueintlist(a, b, c, d, e, ...)
####################################################"""

# Hardcoded defaults for well-known system MIB scalars.
# Uses $$MYIPADDRESS$$ SAPRO token so each simulated device gets its own IP in sysName.
SYSTEM_SCALAR_OVERRIDES = {
    "sysDescr": "fixed(DefensePro)",
    "sysObjectID": "fixed(1.3.6.1.4.1.89.1.1.62.16)",
    "sysUpTime": "clock(377152854)",
    "sysContact": "r_lastset(0, 255,)",
    "sysName": "r_lastset(0, 255,DefensePro_$$MYIPADDRESS$$)",
    "sysLocation": "r_lastset(0, 255,)",
    "sysServices": "fixed(3)",
}

# OID labels where IpAddress values should use $$MYIPADDRESS$$ token
MYIP_LABELS = {"ipAdEntAddr", "rsIpAdEntAddr"}

# OID labels where MAC address values should use $$MYMAINMACADDR$$ token
MAC_LABELS = {
    "ifPhysAddress", "dot1dBaseBridgeAddress", "dot3adAggMACAddress",
    "dot3adAggActorSystemID", "dot3adAggPartnerSystemID",
    "dot3adAggPortActorSystemID", "dot3adAggPortPartnerAdminSystemID",
    "dot3adAggPortPartnerOperSystemID", "ipNetToMediaPhysAddress",
    "ip6NetToMediaPhysAddress",
}

# Version-dependent scalar overrides — populated at runtime with detected version
# These use {version} placeholder replaced in __init__
VERSION_SCALAR_OVERRIDES = {
    "rndBrgVersion": "r_lastset(0, 255,{version})",
    "rndApsoluteOSVersion": "fixed(01.00-00.00:{version})",
    "rsWSDUserVersion": "r_lastset(1, 6,{version_short})",
    "rsIDSVersion": "fixed({version})",
}


class VarGenerator:
    """Generate SAPRO .var files with dynamic row creation blocks."""

    def __init__(
        self,
        oid_entries: list[OidEntry],
        dynamic_rows: list[DynamicRowConfig],
        version: str,
        device_driver: str = None,
    ):
        self.entries = oid_entries
        self.dynamic_rows = dynamic_rows
        self.version = version
        self.device_driver = device_driver
        # Version variants for scalar overrides
        # version = "10.12.0.1", version_short = "10.12.0"
        parts = version.split(".")
        self._version_short = ".".join(parts[:3]) if len(parts) >= 3 else version
        # Resolve version-dependent overrides
        self._version_overrides: dict[str, str] = {}
        for label, template in VERSION_SCALAR_OVERRIDES.items():
            self._version_overrides[label] = template.replace(
                "{version}", version
            ).replace("{version_short}", self._version_short)
        # Build entry name -> OID lookup for %drow lines
        self._entry_oid_map: dict[str, str] = {}
        for e in oid_entries:
            if e.is_table_entry:
                self._entry_oid_map[e.label] = e.oid

        # Detect Current (mirror) tables by naming convention.
        # These are read-only tables that the TCL modeling file populates
        # by mirroring from Modify tables. They need %drow newinstance
        # blocks so SA_setvar can create rows in them.
        self._mirror_current_entries: list[str] = []
        drow_entry_names = {dr.entry_name for dr in dynamic_rows}
        for entry_name in self._entry_oid_map:
            if "Current" not in entry_name:
                continue
            # Only add if the Current table doesn't already have a %drow
            if entry_name in drow_entry_names:
                continue
            # Check that a matching Modify table exists
            modify_name = entry_name.replace("Current", "")
            if modify_name not in self._entry_oid_map:
                # Try suffix pattern: XxxCurrentYyy -> XxxYyy
                parts = entry_name.split("Current")
                if len(parts) == 2:
                    modify_name = parts[0] + parts[1]
            if modify_name in drow_entry_names:
                self._mirror_current_entries.append(entry_name)

    def generate(self) -> str:
        """Generate VAR content and return as string."""
        lines: list[str] = []

        # File header
        lines.append(VAR_HEADER.format(date=datetime.now().strftime("%a %b %d %H:%M:%S %Y")))

        # Dynamic row creation blocks
        for i, config in enumerate(self.dynamic_rows):
            drow_lines = self._write_dynamic_rows(config)
            lines.extend(drow_lines)
            if i < len(self.dynamic_rows) - 1:
                lines.append("#")

        # Dynamic row blocks for Current (mirror) tables
        if self._mirror_current_entries:
            lines.append("#")
            lines.append("# Current table dynamic row templates (for TCL mirroring)")
            for current_entry in self._mirror_current_entries:
                mirror_lines = self._write_mirror_drow(current_entry)
                if mirror_lines:
                    lines.extend(mirror_lines)
                    lines.append("#")

        # Scalar variables only — sorted by OID (lexicographic order)
        # Table columns are NOT included: tables start empty and get
        # populated at runtime via dynamic rows or SNMP sets.
        scalars = [
            e for e in self.entries
            if e.index_type == "S" and not e.is_table_entry
        ]
        scalars.sort(key=lambda e: [int(x) for x in e.oid.split(".")])

        for entry in scalars:
            lines.append(self._write_scalar(entry))

        content = "\n".join(lines) + "\n"
        logger.info("Generated VAR content")
        return content

    def _write_scalar(self, entry: OidEntry) -> str:
        # Device driver scalar
        if entry.label == "rndVisionDriverActiveName" and self.device_driver:
            value_info = f"fixed({self.device_driver})"
        # Version-dependent scalars
        elif entry.label in self._version_overrides:
            value_info = self._version_overrides[entry.label]
        # System scalar overrides
        elif entry.label in SYSTEM_SCALAR_OVERRIDES:
            value_info = SYSTEM_SCALAR_OVERRIDES[entry.label]
        else:
            value_info = self._get_value_info(entry)
        access = self._format_access(entry)
        padding = " " * max(1, 30 - len(entry.label) - 2)
        return f"{entry.label}.0{padding}, {entry.syntax:<12}, {access} , {value_info}"

    def _write_mirror_drow(self, current_entry_name: str) -> list[str]:
        """Generate a %drow newinstance block for a Current (mirror) table."""
        entry_oid = self._entry_oid_map.get(current_entry_name)
        if not entry_oid:
            return []

        table_name = current_entry_name.replace("Entry", "Table")
        columns = [
            e for e in self.entries
            if e.is_table_column and e.table_name == table_name
        ]
        if not columns:
            columns = [
                e for e in self.entries
                if e.is_table_column and e.entry_name == current_entry_name
            ]
        if not columns:
            return []

        columns.sort(key=lambda c: [int(x) for x in c.oid.split(".")])
        index_labels = {c.label for c in columns if c.access == AccessLevel.NA}

        lines = [f"%drow  {entry_oid}   newinstance"]
        for col in columns:
            is_index = col.label in index_labels
            if is_index:
                required, access = "NotReq", "NA"
                value_info = {"OctetString": "dfixed(abc)", "Integer": "dfixed(1)",
                              "IpAddress": "dfixed(1.2.3.4)", "ObjectID": "dfixed(1.2.3)"
                              }.get(col.syntax, "dfixed(0)")
            else:
                required, access = "NotReq", "RO"
                value_info = self._get_ro_default(col.syntax, col.label)

            label_padded = col.label + " " * max(1, 40 - len(col.label))
            lines.append(f"%dcol  {label_padded}{required:<7} {col.syntax:<12} {access} {value_info}")

        return lines

    def _write_dynamic_rows(self, config: DynamicRowConfig) -> list[str]:
        lines: list[str] = []
        prefix = "#" if not config.is_fully_detected else ""

        # Use OID path for entry — SAPRO needs it to look up index info from CMF
        entry_oid = self._entry_oid_map.get(config.entry_name, config.entry_name)
        lines.append(f"{prefix}%drow  {entry_oid}   {config.row_type.value}")

        for dcol in config.columns:
            label_padded = dcol.label + " " * max(1, 40 - len(dcol.label))
            lines.append(
                f"{prefix}%dcol  {label_padded}{dcol.required:<7} {dcol.syntax:<12} {dcol.access} {dcol.value_info}"
            )

        if config.row_type == DynamicRowType.NEWINSTANCE:
            if config.is_fully_detected and config.setaction_column:
                col_padded = f"{config.setaction_column:<25}"
                lines.append(
                    f"%setaction {col_padded}{config.setaction_type:<12} {config.setaction_value} deleterow()"
                )
            else:
                lines.append(
                    f"#%setaction {'<unknown_column>':<25}{'<unknown_type>':<12} <specify value> deleterow()"
                )

        return lines

    def _get_value_info(self, entry: OidEntry, is_index: bool = False) -> str:
        syntax = entry.syntax
        access = entry.access.value

        if is_index:
            return self._get_index_default(entry)

        # Use $$MYIPADDRESS$$ for OIDs that represent the device's own IP
        if entry.label in MYIP_LABELS and syntax == "IpAddress":
            return "fixed($$MYIPADDRESS$$)"

        # Use $$MYMAINMACADDR$$ for MAC address OIDs
        if entry.label in MAC_LABELS:
            return "fixed($$MYMAINMACADDR$$)"

        has_range = entry.min_range is not None and entry.max_range is not None

        if access in ("RW", "Create", "RC"):
            if has_range:
                return f"r_lastset({entry.min_range}, {entry.max_range},{self._get_midpoint(entry)})"
            return self._get_rw_default(syntax, entry.label)
        else:
            return self._get_ro_default(syntax, entry.label)

    def _format_access(self, entry: OidEntry) -> str:
        access = entry.access.value
        if access == "Create":
            return "RC"
        if access == "NA":
            return "NA"
        return access

    def _get_midpoint(self, entry: OidEntry) -> str:
        syntax = entry.syntax
        if syntax == "IpAddress":
            return "$$MYIPADDRESS$$"
        if syntax == "OctetString":
            size = entry.max_range if entry.max_range else 255
            label_trunc = f"My_{entry.label}"[:size] if size > 4 else "abc"
            return label_trunc
        if syntax == "ObjectID":
            return "1.2.3"
        if entry.min_range is not None and entry.max_range is not None:
            if entry.has_enum and entry.enum_values:
                first_val = min(entry.enum_values.values())
                return str(first_val)
            mid = (entry.min_range + entry.max_range) // 2
            return str(mid)
        return "0"

    def _get_ro_default(self, syntax: str, label: str) -> str:
        """SAPRO algorithm for Read-Only variables."""
        defaults = {
            "Counter": "randomup(0, 100)",
            "Counter64": "randomup(0, 100)",
            "Gauge": "fixed(0)",
            "OctetString": f"fixed(My_{label})",
            "TimeTicks": "clock(0)",
            "Integer": "fixed(1)",
            "IpAddress": "fixed($$MYIPADDRESS$$)",
            "ObjectID": "fixed(1.3.6.1.4.1.89)",
            "Bits": "fixed(0x00)",
            "Opaque": "fixed(0x00)",
        }
        return defaults.get(syntax, "fixed(0)")

    def _get_rw_default(self, syntax: str, label: str) -> str:
        """SAPRO algorithm for Read-Write variables."""
        defaults = {
            "Counter": "lastset(0)",
            "Counter64": "lastset(0)",
            "Gauge": "lastset(0)",
            "OctetString": f"lastset(My_{label})",
            "TimeTicks": "lastset(0)",
            "Integer": "lastset(1)",
            "IpAddress": "lastset($$MYIPADDRESS$$)",
            "ObjectID": "lastset(1.3.6.1.4.1.89)",
            "Bits": "lastset(0x00)",
            "Opaque": "lastset(0x00)",
        }
        return defaults.get(syntax, "lastset(0)")

    def _get_index_default(self, entry: OidEntry) -> str:
        syntax = entry.syntax
        if syntax == "IpAddress":
            if entry.label in MYIP_LABELS:
                return "fixed($$MYIPADDRESS$$)"
            return "fixed(1.2.3.4)"
        if syntax == "Integer":
            return "fixed(1)"
        if syntax == "OctetString":
            return "fixed(abc)"
        if syntax == "ObjectID":
            return "fixed(1.2.3)"
        return "fixed(0)"
