import logging
from datetime import datetime
from pathlib import Path

from backend.app.modules.sapro.oid_compiler.constants import RO_DEFAULTS, RW_DEFAULTS, SYNTAX_MAP
from backend.app.modules.sapro.oid_compiler.models import (
    AccessLevel,
    DynamicRowConfig,
    DynamicRowType,
    OidEntry,
)

logger = logging.getLogger(__name__)


class VarGenerator:
    """Generate SAPRO .var files with scalars, tables, and dynamic row creation."""

    DEFAULT_NUM_ROWS = 2

    def __init__(
        self,
        oid_entries: list[OidEntry],
        dynamic_rows: list[DynamicRowConfig],
        version: str,
        num_rows: int = 2,
    ):
        self.entries = oid_entries
        self.dynamic_rows = dynamic_rows
        self.version = version
        self.num_rows = num_rows

    def generate(self, output_path: str) -> str:
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)

        lines: list[str] = []

        # File header
        lines.append("# ============================================")
        lines.append("# Generated by Simulator Tools MIB Compiler")
        lines.append(f"# DefensePro version: {self.version}")
        lines.append(f"# Generated: {datetime.now().strftime('%Y-%m-%d')}")
        lines.append("# ============================================")
        lines.append("")

        # Scalars
        scalars = [e for e in self.entries if e.index_type == "S" and not e.is_table_entry]
        if scalars:
            lines.append("# --- Scalars ---")
            for entry in scalars:
                lines.append(self._write_scalar(entry))
            lines.append("")

        # Static tables
        table_columns: dict[str, list[OidEntry]] = {}
        for e in self.entries:
            if e.is_table_column and e.table_name:
                table_columns.setdefault(e.table_name, []).append(e)

        dynamic_entry_names = {dr.entry_name for dr in self.dynamic_rows}

        for table_name, columns in sorted(table_columns.items()):
            # Skip tables that have dynamic row creation
            entry_name = table_name.replace("Table", "Entry")
            if entry_name in dynamic_entry_names:
                continue
            table_lines = self._write_table(table_name, columns)
            lines.extend(table_lines)
            lines.append("")

        # Dynamic row creation section
        if self.dynamic_rows:
            lines.append("# =============================================")
            lines.append("# Dynamic Row Creation Definitions")
            lines.append("# =============================================")
            lines.append("")

            for config in self.dynamic_rows:
                drow_lines = self._write_dynamic_rows(config)
                lines.extend(drow_lines)
                lines.append("")

        content = "\n".join(lines)
        output.write_text(content, encoding="utf-8")
        logger.info(f"Generated VAR file: {output}")
        return str(output)

    def _write_scalar(self, entry: OidEntry) -> str:
        value_info = self._get_value_info(entry)
        syntax = entry.syntax
        access = entry.access.value if entry.access.value != "Create" else "RW"
        return f"# {entry.label}\n{entry.oid}.0 , {syntax} , {access} , {value_info}"

    def _write_table(self, table_name: str, columns: list[OidEntry]) -> list[str]:
        lines: list[str] = []
        columns.sort(key=lambda c: [int(x) for x in c.oid.split(".")])

        lines.append(f"# --- Table: {table_name} ({self.num_rows} rows) ---")
        lines.append(f"%sapdefine NUMROWS_{table_name} {self.num_rows}")
        lines.append("")

        index_labels = set()
        if columns:
            index_labels = set(columns[0].index_columns)

        for col in columns:
            is_index = col.label in index_labels
            value_info = self._get_value_info(col, is_index=is_index)
            syntax = col.syntax
            access = col.access.value if col.access.value != "Create" else "RW"

            lines.append(f"# {col.label}")
            lines.append(
                f"{col.oid}.[1-NUMROWS_{table_name}] , {syntax} , {access} , {value_info}"
            )

        return lines

    def _write_dynamic_rows(self, config: DynamicRowConfig) -> list[str]:
        lines: list[str] = []
        prefix = "#" if not config.is_fully_detected else ""

        if not config.is_fully_detected:
            lines.append(
                f"# WARNING: Table {config.entry_name.replace('Entry', 'Table')} "
                f"may support dynamic row creation (has RW columns)"
            )
            lines.append(
                "# but the delete-action column and value could not be auto-detected."
            )
            lines.append(
                "# To enable, uncomment the block below and configure the %setaction line."
            )

        type_label = config.row_type.value
        lines.append(
            f"# --- Table: {config.entry_name} ({type_label}) ---"
        )
        lines.append(f"{prefix}%drow {config.entry_name} {type_label}")

        for dcol in config.columns:
            lines.append(
                f"{prefix}%dcol {dcol.label} {dcol.required} {dcol.syntax} "
                f"{dcol.access} {dcol.value_info}"
            )

        if config.row_type == DynamicRowType.NEWINSTANCE:
            if config.is_fully_detected and config.setaction_column:
                lines.append(
                    f"%setaction {config.setaction_column} {config.setaction_type} "
                    f"{config.setaction_value} deleterow()"
                )
            elif not config.is_fully_detected:
                lines.append(
                    f"#%setaction <unknown_column> <unknown_type> <unknown_value> deleterow()"
                )

        return lines

    def _get_value_info(self, entry: OidEntry, is_index: bool = False) -> str:
        syntax = entry.syntax

        if is_index:
            return "indexvalue(0)"

        access = entry.access
        if access in (AccessLevel.RW, AccessLevel.CREATE):
            template = RW_DEFAULTS.get(syntax, "lastset(0)")
        else:
            template = RO_DEFAULTS.get(syntax, "fixed(0)")

        if "{label}" in template:
            template = template.replace("{label}", f"My_{entry.label}")

        return template
